version: '3.1'
services:
  pg:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=englishcenter_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data: